use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use serde_json::{json, Value};

use crate::protocol::agents::*;
use crate::protocol::epic::ExecutionStatus;

/// 多代理编排器——管理、分发和监控编码代理
pub struct AgentOrchestrator {
    agents: Vec<AgentConfig>,
}

impl AgentOrchestrator {
    /// 创建编排器，预注册默认代理
    pub fn new() -> Self {
        let mut orchestrator = Self { agents: vec![] };
        orchestrator.register_defaults();
        orchestrator
    }

    /// 注册一个代理
    pub fn register_agent(&mut self, config: AgentConfig) {
        // 如果 ID 已存在则替换
        self.agents.retain(|a| a.id != config.id);
        self.agents.push(config);
    }

    /// 列出所有注册的代理
    pub fn list_agents(&self) -> Vec<AgentConfig> {
        self.agents.clone()
    }

    /// 获取指定代理的配置
    pub fn get_agent(&self, agent_id: &str) -> Option<&AgentConfig> {
        self.agents.iter().find(|a| a.id == agent_id)
    }

    /// 向指定代理发起交接
    ///
    /// 对于 CLI 代理：生成 handoff markdown 文件
    /// 对于 API 代理：发送 HTTP 请求（当前版本生成 markdown）
    pub async fn handoff(
        &self,
        payload: HandoffPayload,
        agent_id: &str,
    ) -> Result<HandoffResult, String> {
        let agent = self
            .get_agent(agent_id)
            .ok_or_else(|| format!("代理 '{}' 未注册", agent_id))?;

        match &agent.agent_type {
            AgentType::Custom if agent.endpoint.is_some() => {
                // API 代理——发送 HTTP 请求
                self.handoff_via_api(payload, agent).await
            }
            _ => {
                // CLI 代理——生成 handoff markdown
                self.handoff_via_cli(payload, agent).await
            }
        }
    }

    /// 生成交接 Markdown——用于粘贴到目标代理
    pub fn format_handoff_markdown(&self, payload: &HandoffPayload) -> String {
        let mut md = String::new();

        md.push_str("# Agent Handoff\n\n");

        // 工单信息（Traycer Ticket 没有 priority / dependencies / labels / estimated_effort 字段）
        md.push_str("## Ticket\n\n");
        md.push_str(&format!("- **ID**: {}\n", payload.ticket.id.0));
        md.push_str(&format!("- **Title**: {}\n", payload.ticket.title));
        if let Some(ref assignee) = payload.ticket.assignee {
            md.push_str(&format!("- **Assignee**: {}\n", assignee));
        }
        md.push_str(&format!(
            "- **Description**: {}\n\n",
            payload.ticket.description
        ));

        // 计划快照
        md.push_str("## Plan Snapshot\n\n");
        md.push_str("```\n");
        md.push_str(&payload.plan_snapshot);
        md.push_str("\n```\n\n");

        // 指令
        md.push_str("## Instructions\n\n");
        md.push_str(&payload.instructions);
        md.push_str("\n\n");

        // 上下文文件
        if !payload.context_files.is_empty() {
            md.push_str("## Context Files\n\n");
            for file in &payload.context_files {
                md.push_str(&format!("### `{}` ({})\n\n", file.path, file.language));
                md.push_str(&format!("```{}\n", file.language));
                md.push_str(&file.content);
                md.push_str("\n```\n\n");
            }
        }

        // 验证提示
        if let Some(ref prompt) = payload.verification_prompt {
            md.push_str("## Verification Prompt\n\n");
            md.push_str(prompt);
            md.push_str("\n\n");
        }

        md.push_str("---\n");
        md.push_str("*Generated by ClearLoop Agent Orchestrator*\n");

        md
    }

    /// CLI 代理交接——生成可由 Codex CLI / Claude Code CLI 消费的本地运行脚手架。
    async fn handoff_via_cli(
        &self,
        payload: HandoffPayload,
        agent: &AgentConfig,
    ) -> Result<HandoffResult, String> {
        let markdown = self.format_handoff_markdown(&payload);
        let execution_id = uuid::Uuid::new_v4().to_string();
        let scaffold = create_cli_handoff_scaffold(&execution_id, &payload, agent, &markdown)?;

        tracing::info!(
            agent_id = %agent.id,
            ticket_id = %payload.ticket.id.0,
            markdown_len = markdown.len(),
            handoff_path = %scaffold.handoff_path.display(),
            "生成了 CLI agent handoff 脚手架"
        );

        Ok(HandoffResult {
            agent_id: agent.id.clone(),
            execution_id,
            status: ExecutionStatus::WaitingForExecution,
            files_changed: vec![],
            artifacts: scaffold.artifacts,
            handoff_path: Some(scaffold.handoff_path.display().to_string()),
            command_hint: Some(scaffold.command_hint),
            commit_sha: None,
            duration_ms: None,
        })
    }

    /// API 代理交接——通过 HTTP 发送任务
    async fn handoff_via_api(
        &self,
        payload: HandoffPayload,
        agent: &AgentConfig,
    ) -> Result<HandoffResult, String> {
        let endpoint = agent
            .endpoint
            .as_ref()
            .ok_or_else(|| format!("代理 '{}' 没有配置 endpoint", agent.id))?;

        let client = reqwest::Client::new();
        let body =
            serde_json::to_value(&payload).map_err(|e| format!("序列化 payload 失败: {}", e))?;

        let execution_id = uuid::Uuid::new_v4().to_string();

        let resp = client
            .post(endpoint)
            .json(&body)
            .send()
            .await
            .map_err(|e| format!("API 交接请求失败: {}", e))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            return Err(format!("API 代理返回错误 {}: {}", status, text));
        }

        // 尝试解析响应为 HandoffResult
        let result: HandoffResult = resp.json().await.unwrap_or(HandoffResult {
            agent_id: agent.id.clone(),
            execution_id,
            // 旧 Running → Traycer InProgress
            status: ExecutionStatus::InProgress,
            files_changed: vec![],
            artifacts: vec![],
            handoff_path: None,
            command_hint: None,
            commit_sha: None,
            duration_ms: None,
        });

        Ok(result)
    }

    /// 注册默认代理
    fn register_defaults(&mut self) {
        self.agents.push(AgentConfig {
            id: "claude-code".into(),
            name: "Claude Code".into(),
            agent_type: AgentType::ClaudeCode,
            command: Some("claude".into()),
            endpoint: None,
            capabilities: vec![
                "plan".into(),
                "implement".into(),
                "review".into(),
                "refactor".into(),
                "test".into(),
            ],
        });

        self.agents.push(AgentConfig {
            id: "codex-cli".into(),
            name: "Codex CLI".into(),
            agent_type: AgentType::Custom,
            command: Some("codex".into()),
            endpoint: None,
            capabilities: vec![
                "plan".into(),
                "implement".into(),
                "review".into(),
                "test".into(),
                "terminal".into(),
            ],
        });

        self.agents.push(AgentConfig {
            id: "cursor".into(),
            name: "Cursor".into(),
            agent_type: AgentType::Cursor,
            command: Some("cursor".into()),
            endpoint: None,
            capabilities: vec!["implement".into(), "review".into(), "refactor".into()],
        });

        self.agents.push(AgentConfig {
            id: "copilot".into(),
            name: "GitHub Copilot".into(),
            agent_type: AgentType::Copilot,
            command: None,
            endpoint: None,
            capabilities: vec!["implement".into(), "suggest".into()],
        });
    }
}

#[derive(Debug)]
struct HandoffScaffold {
    handoff_path: PathBuf,
    command_hint: String,
    artifacts: Vec<String>,
}

fn create_cli_handoff_scaffold(
    execution_id: &str,
    payload: &HandoffPayload,
    agent: &AgentConfig,
    markdown: &str,
) -> Result<HandoffScaffold, String> {
    let workspace_root = workspace_root();
    create_cli_handoff_scaffold_in(&workspace_root, execution_id, payload, agent, markdown)
}

fn create_cli_handoff_scaffold_in(
    workspace_root: &Path,
    execution_id: &str,
    payload: &HandoffPayload,
    agent: &AgentConfig,
    markdown: &str,
) -> Result<HandoffScaffold, String> {
    let created_at = chrono::Utc::now();
    let run_id = format!(
        "{}-{}",
        created_at.format("%Y%m%dT%H%M%SZ"),
        safe_segment(&format!("{}-{}", agent.id, execution_id))
    );
    let run_dir = workspace_root
        .join(".bestqa")
        .join("agent-runs")
        .join(&run_id);

    fs::create_dir_all(&run_dir)
        .map_err(|e| format!("创建 handoff 目录失败 {}: {}", run_dir.display(), e))?;

    let handoff_path = run_dir.join("handoff.md");
    let manifest_path = run_dir.join("manifest.json");
    let evidence_path = run_dir.join("evidence.jsonl");
    let commands_path = run_dir.join("commands.jsonl");
    let changes_path = run_dir.join("changes.json");
    let verification_path = run_dir.join("verification.md");
    let readme_path = run_dir.join("README.md");
    let result_path = run_dir.join("result.md");

    fs::write(&handoff_path, markdown)
        .map_err(|e| format!("写入 handoff.md 失败 {}: {}", handoff_path.display(), e))?;

    let command_hint = command_hint(agent, &handoff_path);
    let created_at_rfc3339 = created_at.to_rfc3339();
    let manifest = json!({
        "schema_version": "run-ledger.v1",
        "run_id": run_id,
        "execution_id": execution_id,
        "workspace": workspace_root.display().to_string(),
        "status": "WAITING_FOR_EXECUTION",
        "agent": {
            "id": agent.id,
            "name": agent.name,
            "kind": agent_kind(agent),
            "command": agent.command,
        },
        "workflow": {
            "stage": "handoff",
            "baseline": "intent->clarification->plan->execution->verification->memory",
        },
        "task": {
            "ticket_id": payload.ticket.id.0,
            "epic_id": payload.ticket.epic_id.0,
            "title": payload.ticket.title,
            "intent": payload.ticket.description,
            "acceptance": payload.verification_prompt.iter().collect::<Vec<_>>(),
        },
        "paths": {
            "run_dir": run_dir.display().to_string(),
            "handoff": handoff_path.display().to_string(),
            "evidence": evidence_path.display().to_string(),
            "commands": commands_path.display().to_string(),
            "changes": changes_path.display().to_string(),
            "verification": verification_path.display().to_string(),
            "result": result_path.display().to_string(),
        },
        "memory_gate": {
            "decision": "not_evaluated",
            "reason": "No verification record yet",
        },
        "created_at": created_at_rfc3339,
    });
    let manifest_json = serde_json::to_string_pretty(&manifest)
        .map_err(|e| format!("序列化 handoff manifest 失败: {}", e))?;
    fs::write(&manifest_path, manifest_json)
        .map_err(|e| format!("写入 manifest.json 失败 {}: {}", manifest_path.display(), e))?;

    let evidence = json!({
        "ts": created_at_rfc3339,
        "type": "handoff_created",
        "run_id": run_id,
        "ticket_id": payload.ticket.id.0,
        "agent_id": agent.id,
        "status": "WAITING_FOR_EXECUTION",
        "summary": "ClearLoop created a CLI handoff. Execution has not started.",
    });
    fs::write(&evidence_path, format!("{}\n", evidence)).map_err(|e| {
        format!(
            "写入 evidence.jsonl 失败 {}: {}",
            evidence_path.display(),
            e
        )
    })?;

    let command_event = json!({
        "ts": created_at_rfc3339,
        "type": "suggested_command",
        "agent_id": agent.id,
        "command_hint": command_hint,
        "status": "not_run",
    });
    fs::write(&commands_path, format!("{}\n", command_event)).map_err(|e| {
        format!(
            "写入 commands.jsonl 失败 {}: {}",
            commands_path.display(),
            e
        )
    })?;

    let changes = json!({
        "schema_version": "run-ledger.v1",
        "status": "not_run",
        "changed_files": [],
        "note": "No file changes have been recorded. The CLI agent has not executed yet.",
    });
    let changes_json = serde_json::to_string_pretty(&changes)
        .map_err(|e| format!("序列化 changes.json 失败: {}", e))?;
    fs::write(&changes_path, changes_json)
        .map_err(|e| format!("写入 changes.json 失败 {}: {}", changes_path.display(), e))?;

    fs::write(&verification_path, render_verification_markdown(payload)).map_err(|e| {
        format!(
            "写入 verification.md 失败 {}: {}",
            verification_path.display(),
            e
        )
    })?;

    fs::write(&readme_path, render_scaffold_readme(agent, &command_hint))
        .map_err(|e| format!("写入 README.md 失败 {}: {}", readme_path.display(), e))?;
    fs::write(&result_path, render_result_markdown())
        .map_err(|e| format!("写入 result.md 失败 {}: {}", result_path.display(), e))?;

    let artifacts = vec![
        handoff_path.display().to_string(),
        manifest_path.display().to_string(),
        evidence_path.display().to_string(),
        commands_path.display().to_string(),
        changes_path.display().to_string(),
        verification_path.display().to_string(),
        readme_path.display().to_string(),
        result_path.display().to_string(),
    ];

    Ok(HandoffScaffold {
        handoff_path,
        command_hint,
        artifacts,
    })
}

pub fn record_run_ledger_result(
    params: RunLedgerRecordParams,
) -> Result<RunLedgerRecordResult, String> {
    let workspace_root = workspace_root();
    record_run_ledger_result_in(&workspace_root, params)
}

fn record_run_ledger_result_in(
    workspace_root: &Path,
    params: RunLedgerRecordParams,
) -> Result<RunLedgerRecordResult, String> {
    let run_dir = resolve_run_dir(workspace_root, &params.run_dir)?;
    let manifest_path = run_dir.join("manifest.json");
    let evidence_path = run_dir.join("evidence.jsonl");
    let commands_path = run_dir.join("commands.jsonl");
    let changes_path = run_dir.join("changes.json");
    let verification_path = run_dir.join("verification.md");
    let result_path = run_dir.join("result.md");

    let now = chrono::Utc::now().to_rfc3339();
    let status = normalize_ledger_status(&params.status)?;
    let mut manifest: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path)
            .map_err(|e| format!("读取 manifest.json 失败 {}: {}", manifest_path.display(), e))?,
    )
    .map_err(|e| format!("解析 manifest.json 失败 {}: {}", manifest_path.display(), e))?;

    let run_id = manifest
        .get("run_id")
        .and_then(Value::as_str)
        .unwrap_or("unknown")
        .to_string();

    manifest["status"] = json!(status);
    manifest["updated_at"] = json!(now.clone());
    manifest["result_summary"] = json!(&params.summary);
    manifest["workflow"]["stage"] = json!(ledger_stage_for_status(status));
    if let Some(memory_gate) = &params.memory_gate {
        manifest["memory_gate"] = json!({
            "decision": memory_gate.decision,
            "reason": memory_gate.reason,
        });
    }

    fs::write(
        &manifest_path,
        serde_json::to_string_pretty(&manifest)
            .map_err(|e| format!("序列化 manifest.json 失败: {}", e))?,
    )
    .map_err(|e| format!("写入 manifest.json 失败 {}: {}", manifest_path.display(), e))?;

    let changes = json!({
        "schema_version": "run-ledger.v1",
        "status": status,
        "changed_files": &params.changed_files,
        "updated_at": now.clone(),
        "note": if params.changed_files.is_empty() {
            "No changed files were reported."
        } else {
            "Changed files were reported by the agent or runner."
        },
    });
    fs::write(
        &changes_path,
        serde_json::to_string_pretty(&changes)
            .map_err(|e| format!("序列化 changes.json 失败: {}", e))?,
    )
    .map_err(|e| format!("写入 changes.json 失败 {}: {}", changes_path.display(), e))?;

    for command in &params.commands {
        append_jsonl(
            &commands_path,
            json!({
                "ts": now.clone(),
                "type": "command_recorded",
                "run_id": &run_id,
                "command": &command.command,
                "status": &command.status,
                "summary": &command.summary,
                "output_path": &command.output_path,
            }),
        )?;
    }

    append_jsonl(
        &evidence_path,
        json!({
            "ts": now.clone(),
            "type": "result_recorded",
            "run_id": &run_id,
            "status": status,
            "summary": &params.summary,
            "changed_files_count": params.changed_files.len(),
            "command_count": params.commands.len(),
        }),
    )?;
    if let Some(verification) = &params.verification {
        append_jsonl(
            &evidence_path,
            json!({
                "ts": now.clone(),
                "type": "verification_recorded",
                "run_id": &run_id,
                "status": status,
                "summary": verification,
            }),
        )?;
    }

    fs::write(
        &verification_path,
        render_recorded_verification_markdown(&params, status),
    )
    .map_err(|e| {
        format!(
            "写入 verification.md 失败 {}: {}",
            verification_path.display(),
            e
        )
    })?;
    fs::write(
        &result_path,
        render_recorded_result_markdown(&params, status),
    )
    .map_err(|e| format!("写入 result.md 失败 {}: {}", result_path.display(), e))?;

    Ok(RunLedgerRecordResult {
        run_dir: run_dir.display().to_string(),
        status: status.to_string(),
        changed_files_count: params.changed_files.len(),
        command_count: params.commands.len(),
        artifacts: vec![
            manifest_path.display().to_string(),
            evidence_path.display().to_string(),
            commands_path.display().to_string(),
            changes_path.display().to_string(),
            verification_path.display().to_string(),
            result_path.display().to_string(),
        ],
    })
}

fn resolve_run_dir(workspace_root: &Path, run_dir: &str) -> Result<PathBuf, String> {
    let raw = PathBuf::from(run_dir);
    let candidate = if raw.is_absolute() {
        raw
    } else {
        workspace_root.join(raw)
    };
    let canonical_run_dir = fs::canonicalize(&candidate)
        .map_err(|e| format!("run_dir 不存在或不可访问 {}: {}", candidate.display(), e))?;
    let ledger_root = workspace_root.join(".bestqa").join("agent-runs");
    let canonical_ledger_root = fs::canonicalize(&ledger_root).map_err(|e| {
        format!(
            "Run Ledger 根目录不存在或不可访问 {}: {}",
            ledger_root.display(),
            e
        )
    })?;
    if !canonical_run_dir.starts_with(&canonical_ledger_root) {
        return Err(format!(
            "拒绝写入工作区 Run Ledger 之外的目录: {}",
            canonical_run_dir.display()
        ));
    }
    for required in [
        "manifest.json",
        "evidence.jsonl",
        "commands.jsonl",
        "changes.json",
        "verification.md",
        "result.md",
    ] {
        let path = canonical_run_dir.join(required);
        if !path.exists() {
            return Err(format!("Run Ledger 缺少必要文件 {}", path.display()));
        }
    }
    Ok(canonical_run_dir)
}

fn normalize_ledger_status(status: &str) -> Result<&'static str, String> {
    match status.trim().to_ascii_uppercase().as_str() {
        "WAITING_FOR_REVIEW" => Ok("WAITING_FOR_REVIEW"),
        "VERIFIED" => Ok("VERIFIED"),
        "FAILED_VERIFICATION" => Ok("FAILED_VERIFICATION"),
        "CANCELLED" => Ok("CANCELLED"),
        "RUNNING" => Ok("RUNNING"),
        other => Err(format!(
            "不支持的 Run Ledger 状态 '{}'; expected RUNNING, WAITING_FOR_REVIEW, VERIFIED, FAILED_VERIFICATION, or CANCELLED",
            other
        )),
    }
}

fn ledger_stage_for_status(status: &str) -> &'static str {
    match status {
        "RUNNING" => "execution",
        "WAITING_FOR_REVIEW" => "review",
        "VERIFIED" => "verification",
        "FAILED_VERIFICATION" => "verification",
        "CANCELLED" => "cancelled",
        _ => "result",
    }
}

fn append_jsonl(path: &Path, event: Value) -> Result<(), String> {
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .map_err(|e| format!("打开 JSONL 文件失败 {}: {}", path.display(), e))?;
    writeln!(file, "{}", event)
        .map_err(|e| format!("追加 JSONL 事件失败 {}: {}", path.display(), e))
}

fn render_recorded_verification_markdown(params: &RunLedgerRecordParams, status: &str) -> String {
    let mut md = String::new();
    md.push_str("# Verification\n\n");
    md.push_str(&format!("Status: `{}`\n\n", status));
    md.push_str("## Result\n\n");
    md.push_str(
        params
            .verification
            .as_deref()
            .filter(|s| !s.trim().is_empty())
            .unwrap_or("No verification detail was recorded."),
    );
    md.push_str("\n\n## Commands\n\n");
    if params.commands.is_empty() {
        md.push_str("- No commands were recorded.\n");
    } else {
        for command in &params.commands {
            md.push_str(&format!("- `{}` -> `{}`", command.command, command.status));
            if let Some(summary) = &command.summary {
                if !summary.trim().is_empty() {
                    md.push_str(&format!(": {}", summary));
                }
            }
            md.push('\n');
        }
    }
    md.push_str("\n## Residual Risk\n\n");
    md.push_str(
        params
            .residual_risk
            .as_deref()
            .filter(|s| !s.trim().is_empty())
            .unwrap_or("No residual risk was recorded."),
    );
    md.push('\n');
    md
}

fn render_recorded_result_markdown(params: &RunLedgerRecordParams, status: &str) -> String {
    let mut md = String::new();
    md.push_str("# Agent Result\n\n");
    md.push_str(&format!("Status: `{}`\n\n", status));
    md.push_str("## Summary\n\n");
    md.push_str(if params.summary.trim().is_empty() {
        "No summary was recorded."
    } else {
        params.summary.as_str()
    });
    md.push_str("\n\n## Changed Files\n\n");
    if params.changed_files.is_empty() {
        md.push_str("- None reported.\n");
    } else {
        for path in &params.changed_files {
            md.push_str(&format!("- `{}`\n", path));
        }
    }
    md.push_str("\n## Commands Run\n\n");
    if params.commands.is_empty() {
        md.push_str("- None recorded.\n");
    } else {
        for command in &params.commands {
            md.push_str(&format!("- `{}` -> `{}`", command.command, command.status));
            if let Some(summary) = &command.summary {
                if !summary.trim().is_empty() {
                    md.push_str(&format!(": {}", summary));
                }
            }
            md.push('\n');
        }
    }
    md.push_str("\n## Verification\n\n");
    md.push_str(
        params
            .verification
            .as_deref()
            .filter(|s| !s.trim().is_empty())
            .unwrap_or("No verification detail was recorded."),
    );
    md.push_str("\n\n## Memory Gate\n\n");
    if let Some(memory_gate) = &params.memory_gate {
        md.push_str(&format!(
            "Decision: `{}`\n\nReason: {}\n",
            memory_gate.decision, memory_gate.reason
        ));
    } else {
        md.push_str("Decision: `not_evaluated`\n\nReason: No verified reusable lesson has been extracted.\n");
    }
    md
}

fn workspace_root() -> PathBuf {
    std::env::var("CODESAIL_WORKSPACE_ROOT")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .map(PathBuf::from)
        .or_else(|| std::env::current_dir().ok())
        .unwrap_or_else(|| PathBuf::from("."))
}

fn command_hint(agent: &AgentConfig, handoff_path: &Path) -> String {
    let command = agent.command.as_deref().unwrap_or(&agent.id);
    format!(
        "Open `{}` in {} and execute or paste the handoff deliberately.",
        handoff_path.display(),
        command
    )
}

fn agent_kind(agent: &AgentConfig) -> &'static str {
    if agent.command.is_some() {
        "cli"
    } else if agent.endpoint.is_some() {
        "api"
    } else {
        "extension"
    }
}

fn render_scaffold_readme(agent: &AgentConfig, command_hint: &str) -> String {
    format!(
        "# CLI Agent Handoff\n\n\
This directory is a durable handoff scaffold for `{}`.\n\n\
## Files\n\n\
- `manifest.json` — machine-readable run index.\n\
- `handoff.md` — prompt and evidence bundle for the CLI agent.\n\
- `evidence.jsonl` — append-only evidence events.\n\
- `commands.jsonl` — suggested or executed command events.\n\
- `changes.json` — changed-file summary, empty until execution.\n\
- `verification.md` — verification prompt, commands, and pass/fail notes.\n\
- `result.md` — final result summary, changed files, and residual risks.\n\n\
## Launch\n\n\
{}\n\n\
Keep the result explicit: changed files, commands run, logs, remaining risks.\n",
        agent.name, command_hint
    )
}

fn render_verification_markdown(payload: &HandoffPayload) -> String {
    let mut md = String::new();
    md.push_str("# Verification\n\n");
    md.push_str("Status: `not_run`\n\n");
    md.push_str("## Acceptance Target\n\n");
    if let Some(prompt) = &payload.verification_prompt {
        md.push_str(prompt);
        md.push_str("\n\n");
    } else {
        md.push_str("No explicit verification prompt was provided. Record the command, observable output, or human acceptance used to verify this run.\n\n");
    }
    md.push_str("## Commands\n\n");
    md.push_str("- [ ] Add verification command and result here.\n\n");
    md.push_str("## Residual Risk\n\n");
    md.push_str("- Not evaluated yet.\n");
    md
}

fn render_result_markdown() -> &'static str {
    "# Agent Result\n\n\
Status: `WAITING_FOR_EXECUTION`\n\n\
## Summary\n\n\
Record the CLI agent result here after execution.\n\n\
## Changed Files\n\n\
- None recorded yet.\n\n\
## Commands Run\n\n\
- None recorded yet.\n\n\
## Verification\n\n\
- Not run yet. Update `verification.md` and append events to `evidence.jsonl` / `commands.jsonl`.\n\n\
## Memory Gate\n\n\
Decision: `not_evaluated`\n\n\
Reason: No verified reusable lesson has been extracted.\n"
}

fn safe_segment(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
            out.push(ch);
        } else {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

impl Default for AgentOrchestrator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::epic::*;

    #[test]
    fn test_default_agents() {
        let orchestrator = AgentOrchestrator::new();
        let agents = orchestrator.list_agents();

        assert_eq!(agents.len(), 4);
        assert!(agents.iter().any(|a| a.id == "claude-code"));
        assert!(agents.iter().any(|a| a.id == "codex-cli"));
        assert!(agents.iter().any(|a| a.id == "cursor"));
        assert!(agents.iter().any(|a| a.id == "copilot"));
    }

    #[test]
    fn test_register_custom_agent() {
        let mut orchestrator = AgentOrchestrator::new();

        orchestrator.register_agent(AgentConfig {
            id: "my-agent".into(),
            name: "My Custom Agent".into(),
            agent_type: AgentType::Custom,
            command: Some("my-agent run".into()),
            endpoint: None,
            capabilities: vec!["implement".into()],
        });

        let agents = orchestrator.list_agents();
        assert_eq!(agents.len(), 5);
        assert!(agents.iter().any(|a| a.id == "my-agent"));
    }

    #[test]
    fn test_register_replaces_existing() {
        let mut orchestrator = AgentOrchestrator::new();

        orchestrator.register_agent(AgentConfig {
            id: "claude-code".into(),
            name: "Custom Claude".into(),
            agent_type: AgentType::ClaudeCode,
            command: Some("claude --custom".into()),
            endpoint: None,
            capabilities: vec![],
        });

        let agents = orchestrator.list_agents();
        // 仍然是 4 个（codex-cli + cursor + copilot + 替换后的 claude-code）
        assert_eq!(agents.len(), 4);
        let claude = agents.iter().find(|a| a.id == "claude-code").unwrap();
        assert_eq!(claude.name, "Custom Claude");
    }

    #[test]
    fn test_get_agent() {
        let orchestrator = AgentOrchestrator::new();
        assert!(orchestrator.get_agent("claude-code").is_some());
        assert!(orchestrator.get_agent("nonexistent").is_none());
    }

    #[test]
    fn test_format_handoff_markdown() {
        let orchestrator = AgentOrchestrator::new();

        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-1".into()),
                epic_id: EpicId("e-1".into()),
                title: "实现用户登录".into(),
                description: "添加 OAuth2 登录支持".into(),
                status: TicketStatus::InProgress,
                assignee: Some("claude-code".into()),
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "Step 1: Add auth middleware\nStep 2: Implement login endpoint".into(),
            context_files: vec![FileContext {
                path: "src/main.rs".into(),
                content: "fn main() {}".into(),
                language: "rust".into(),
            }],
            instructions: "请实现 OAuth2 登录功能".into(),
            verification_prompt: Some("确保密码不以明文存储".into()),
        };

        let md = orchestrator.format_handoff_markdown(&payload);

        assert!(md.contains("# Agent Handoff"));
        assert!(md.contains("实现用户登录"));
        assert!(md.contains("OAuth2"));
        assert!(md.contains("src/main.rs"));
        assert!(md.contains("fn main()"));
        assert!(md.contains("密码不以明文存储"));
        assert!(md.contains("claude-code")); // assignee
    }

    #[test]
    fn test_format_handoff_markdown_minimal() {
        let orchestrator = AgentOrchestrator::new();

        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-1".into()),
                epic_id: EpicId("e-1".into()),
                title: "简单任务".into(),
                description: "做一件事".into(),
                status: TicketStatus::Todo,
                assignee: None,
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "just do it".into(),
            context_files: vec![],
            instructions: "直接做".into(),
            verification_prompt: None,
        };

        let md = orchestrator.format_handoff_markdown(&payload);

        assert!(md.contains("简单任务"));
        // 没有上下文文件时不应出现 Context Files 节
        assert!(!md.contains("Context Files"));
        // 没有验证提示时不应出现 Verification Prompt 节
        assert!(!md.contains("Verification Prompt"));
    }

    #[test]
    fn test_create_cli_handoff_scaffold_writes_run_ledger_v1_files() {
        let orchestrator = AgentOrchestrator::new();
        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-ledger".into()),
                epic_id: EpicId("e-ledger".into()),
                title: "Run ledger smoke".into(),
                description: "Create a durable run ledger scaffold".into(),
                status: TicketStatus::Todo,
                assignee: Some("codex-cli".into()),
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "1. Create scaffold\n2. Verify files".into(),
            context_files: vec![],
            instructions: "Create the handoff only; do not execute.".into(),
            verification_prompt: Some("All run ledger v1 files must exist.".into()),
        };
        let agent = orchestrator.get_agent("codex-cli").unwrap();
        let workspace =
            std::env::temp_dir().join(format!("clearloop-ledger-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&workspace).unwrap();

        let markdown = orchestrator.format_handoff_markdown(&payload);
        let scaffold =
            create_cli_handoff_scaffold_in(&workspace, "exec-ledger", &payload, agent, &markdown)
                .unwrap();
        let run_dir = scaffold.handoff_path.parent().unwrap();

        for name in [
            "manifest.json",
            "handoff.md",
            "evidence.jsonl",
            "commands.jsonl",
            "changes.json",
            "verification.md",
            "README.md",
            "result.md",
        ] {
            assert!(run_dir.join(name).exists(), "{} should exist", name);
        }

        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(run_dir.join("manifest.json")).unwrap())
                .unwrap();
        assert_eq!(manifest["schema_version"], "run-ledger.v1");
        assert_eq!(manifest["status"], "WAITING_FOR_EXECUTION");
        assert_eq!(manifest["agent"]["id"], "codex-cli");
        assert_eq!(manifest["task"]["ticket_id"], "t-ledger");
        assert_eq!(manifest["memory_gate"]["decision"], "not_evaluated");

        let evidence = std::fs::read_to_string(run_dir.join("evidence.jsonl")).unwrap();
        assert!(evidence.contains("\"type\":\"handoff_created\""));
        let commands = std::fs::read_to_string(run_dir.join("commands.jsonl")).unwrap();
        assert!(commands.contains("\"type\":\"suggested_command\""));
        assert_eq!(scaffold.artifacts.len(), 8);

        std::fs::remove_dir_all(&workspace).unwrap();
    }

    #[test]
    fn test_record_run_ledger_result_updates_files() {
        let orchestrator = AgentOrchestrator::new();
        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-record".into()),
                epic_id: EpicId("e-record".into()),
                title: "Record result smoke".into(),
                description: "Record a completed run result".into(),
                status: TicketStatus::Todo,
                assignee: Some("codex-cli".into()),
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "1. Create scaffold\n2. Record result".into(),
            context_files: vec![],
            instructions: "Create the handoff only; do not execute.".into(),
            verification_prompt: Some("Result must be recorded.".into()),
        };
        let agent = orchestrator.get_agent("codex-cli").unwrap();
        let workspace =
            std::env::temp_dir().join(format!("clearloop-record-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&workspace).unwrap();
        let markdown = orchestrator.format_handoff_markdown(&payload);
        let scaffold =
            create_cli_handoff_scaffold_in(&workspace, "exec-record", &payload, agent, &markdown)
                .unwrap();
        let run_dir = scaffold.handoff_path.parent().unwrap().to_path_buf();

        let result = record_run_ledger_result_in(
            &workspace,
            RunLedgerRecordParams {
                run_dir: run_dir.display().to_string(),
                status: "VERIFIED".into(),
                summary: "Implementation completed and verified.".into(),
                changed_files: vec!["src/example.ts".into()],
                commands: vec![RunLedgerCommandRecord {
                    command: "npm test".into(),
                    status: "passed".into(),
                    summary: Some("all tests passed".into()),
                    output_path: None,
                }],
                verification: Some("npm test passed.".into()),
                residual_risk: Some("No residual risk identified.".into()),
                memory_gate: Some(RunLedgerMemoryGate {
                    decision: "not_evaluated".into(),
                    reason: "Smoke test result only.".into(),
                }),
            },
        )
        .unwrap();

        assert_eq!(result.status, "VERIFIED");
        assert_eq!(result.changed_files_count, 1);
        assert_eq!(result.command_count, 1);
        assert_eq!(result.artifacts.len(), 6);

        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(run_dir.join("manifest.json")).unwrap())
                .unwrap();
        assert_eq!(manifest["status"], "VERIFIED");
        assert_eq!(manifest["workflow"]["stage"], "verification");
        assert_eq!(
            manifest["result_summary"],
            "Implementation completed and verified."
        );

        let changes = std::fs::read_to_string(run_dir.join("changes.json")).unwrap();
        assert!(changes.contains("src/example.ts"));
        let commands = std::fs::read_to_string(run_dir.join("commands.jsonl")).unwrap();
        assert!(commands.contains("\"type\":\"command_recorded\""));
        assert!(commands.contains("npm test"));
        let evidence = std::fs::read_to_string(run_dir.join("evidence.jsonl")).unwrap();
        assert!(evidence.contains("\"type\":\"result_recorded\""));
        assert!(evidence.contains("\"type\":\"verification_recorded\""));
        let result_md = std::fs::read_to_string(run_dir.join("result.md")).unwrap();
        assert!(result_md.contains("Implementation completed and verified."));
        assert!(result_md.contains("src/example.ts"));

        std::fs::remove_dir_all(&workspace).unwrap();
    }

    #[test]
    fn test_record_run_ledger_result_rejects_outside_workspace_ledger() {
        let workspace =
            std::env::temp_dir().join(format!("clearloop-record-root-{}", uuid::Uuid::new_v4()));
        let outside =
            std::env::temp_dir().join(format!("clearloop-record-outside-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(workspace.join(".bestqa").join("agent-runs")).unwrap();
        std::fs::create_dir_all(&outside).unwrap();

        let err = record_run_ledger_result_in(
            &workspace,
            RunLedgerRecordParams {
                run_dir: outside.display().to_string(),
                status: "VERIFIED".into(),
                summary: String::new(),
                changed_files: vec![],
                commands: vec![],
                verification: None,
                residual_risk: None,
                memory_gate: None,
            },
        )
        .unwrap_err();

        assert!(err.contains("Run Ledger 之外"));
        std::fs::remove_dir_all(&workspace).unwrap();
        std::fs::remove_dir_all(&outside).unwrap();
    }
}
