use crate::protocol::agents::*;
use crate::protocol::epic::ExecutionStatus;

/// 多代理编排器——管理、分发和监控编码代理
pub struct AgentOrchestrator {
    agents: Vec<AgentConfig>,
}

impl AgentOrchestrator {
    /// 创建编排器，预注册默认代理
    pub fn new() -> Self {
        let mut orchestrator = Self { agents: vec![] };
        orchestrator.register_defaults();
        orchestrator
    }

    /// 注册一个代理
    pub fn register_agent(&mut self, config: AgentConfig) {
        // 如果 ID 已存在则替换
        self.agents.retain(|a| a.id != config.id);
        self.agents.push(config);
    }

    /// 列出所有注册的代理
    pub fn list_agents(&self) -> Vec<AgentConfig> {
        self.agents.clone()
    }

    /// 获取指定代理的配置
    pub fn get_agent(&self, agent_id: &str) -> Option<&AgentConfig> {
        self.agents.iter().find(|a| a.id == agent_id)
    }

    /// 向指定代理发起交接
    ///
    /// 对于 CLI 代理：生成 handoff markdown 文件
    /// 对于 API 代理：发送 HTTP 请求（当前版本生成 markdown）
    pub async fn handoff(
        &self,
        payload: HandoffPayload,
        agent_id: &str,
    ) -> Result<HandoffResult, String> {
        let agent = self
            .get_agent(agent_id)
            .ok_or_else(|| format!("代理 '{}' 未注册", agent_id))?;

        match &agent.agent_type {
            AgentType::Custom if agent.endpoint.is_some() => {
                // API 代理——发送 HTTP 请求
                self.handoff_via_api(payload, agent).await
            }
            _ => {
                // CLI 代理——生成 handoff markdown
                self.handoff_via_cli(payload, agent).await
            }
        }
    }

    /// 生成交接 Markdown——用于粘贴到目标代理
    pub fn format_handoff_markdown(&self, payload: &HandoffPayload) -> String {
        let mut md = String::new();

        md.push_str("# Agent Handoff\n\n");

        // 工单信息（Traycer Ticket 没有 priority / dependencies / labels / estimated_effort 字段）
        md.push_str("## Ticket\n\n");
        md.push_str(&format!("- **ID**: {}\n", payload.ticket.id.0));
        md.push_str(&format!("- **Title**: {}\n", payload.ticket.title));
        if let Some(ref assignee) = payload.ticket.assignee {
            md.push_str(&format!("- **Assignee**: {}\n", assignee));
        }
        md.push_str(&format!(
            "- **Description**: {}\n\n",
            payload.ticket.description
        ));

        // 计划快照
        md.push_str("## Plan Snapshot\n\n");
        md.push_str("```\n");
        md.push_str(&payload.plan_snapshot);
        md.push_str("\n```\n\n");

        // 指令
        md.push_str("## Instructions\n\n");
        md.push_str(&payload.instructions);
        md.push_str("\n\n");

        // 上下文文件
        if !payload.context_files.is_empty() {
            md.push_str("## Context Files\n\n");
            for file in &payload.context_files {
                md.push_str(&format!("### `{}` ({})\n\n", file.path, file.language));
                md.push_str(&format!("```{}\n", file.language));
                md.push_str(&file.content);
                md.push_str("\n```\n\n");
            }
        }

        // 验证提示
        if let Some(ref prompt) = payload.verification_prompt {
            md.push_str("## Verification Prompt\n\n");
            md.push_str(prompt);
            md.push_str("\n\n");
        }

        md.push_str("---\n");
        md.push_str("*Generated by CodeSail Agent Orchestrator*\n");

        md
    }

    /// CLI 代理交接——生成 markdown 并返回结果
    async fn handoff_via_cli(
        &self,
        payload: HandoffPayload,
        agent: &AgentConfig,
    ) -> Result<HandoffResult, String> {
        let markdown = self.format_handoff_markdown(&payload);
        let execution_id = uuid::Uuid::new_v4().to_string();

        // 在生产环境中，这里会：
        // 1. 将 markdown 写入临时文件
        // 2. 调用 agent.command 启动代理
        // 3. 监控执行结果
        // 当前版本返回"待执行"状态
        tracing::info!(
            agent_id = %agent.id,
            ticket_id = %payload.ticket.id.0,
            markdown_len = markdown.len(),
            "生成了 CLI 交接 markdown"
        );

        Ok(HandoffResult {
            agent_id: agent.id.clone(),
            execution_id,
            // 旧 Pending → Traycer NotStarted（CLI 只是生成了 markdown，尚未真正执行）
            status: ExecutionStatus::NotStarted,
            files_changed: vec![],
            commit_sha: None,
            duration_ms: None,
        })
    }

    /// API 代理交接——通过 HTTP 发送任务
    async fn handoff_via_api(
        &self,
        payload: HandoffPayload,
        agent: &AgentConfig,
    ) -> Result<HandoffResult, String> {
        let endpoint = agent
            .endpoint
            .as_ref()
            .ok_or_else(|| format!("代理 '{}' 没有配置 endpoint", agent.id))?;

        let client = reqwest::Client::new();
        let body = serde_json::to_value(&payload)
            .map_err(|e| format!("序列化 payload 失败: {}", e))?;

        let execution_id = uuid::Uuid::new_v4().to_string();

        let resp = client
            .post(endpoint)
            .json(&body)
            .send()
            .await
            .map_err(|e| format!("API 交接请求失败: {}", e))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            return Err(format!("API 代理返回错误 {}: {}", status, text));
        }

        // 尝试解析响应为 HandoffResult
        let result: HandoffResult = resp
            .json()
            .await
            .unwrap_or(HandoffResult {
                agent_id: agent.id.clone(),
                execution_id,
                // 旧 Running → Traycer InProgress
                status: ExecutionStatus::InProgress,
                files_changed: vec![],
                commit_sha: None,
                duration_ms: None,
            });

        Ok(result)
    }

    /// 注册默认代理
    fn register_defaults(&mut self) {
        self.agents.push(AgentConfig {
            id: "claude-code".into(),
            name: "Claude Code".into(),
            agent_type: AgentType::ClaudeCode,
            command: Some("claude".into()),
            endpoint: None,
            capabilities: vec![
                "plan".into(),
                "implement".into(),
                "review".into(),
                "refactor".into(),
                "test".into(),
            ],
        });

        self.agents.push(AgentConfig {
            id: "cursor".into(),
            name: "Cursor".into(),
            agent_type: AgentType::Cursor,
            command: Some("cursor".into()),
            endpoint: None,
            capabilities: vec![
                "implement".into(),
                "review".into(),
                "refactor".into(),
            ],
        });

        self.agents.push(AgentConfig {
            id: "copilot".into(),
            name: "GitHub Copilot".into(),
            agent_type: AgentType::Copilot,
            command: None,
            endpoint: None,
            capabilities: vec![
                "implement".into(),
                "suggest".into(),
            ],
        });
    }
}

impl Default for AgentOrchestrator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::epic::*;

    #[test]
    fn test_default_agents() {
        let orchestrator = AgentOrchestrator::new();
        let agents = orchestrator.list_agents();

        assert_eq!(agents.len(), 3);
        assert!(agents.iter().any(|a| a.id == "claude-code"));
        assert!(agents.iter().any(|a| a.id == "cursor"));
        assert!(agents.iter().any(|a| a.id == "copilot"));
    }

    #[test]
    fn test_register_custom_agent() {
        let mut orchestrator = AgentOrchestrator::new();

        orchestrator.register_agent(AgentConfig {
            id: "my-agent".into(),
            name: "My Custom Agent".into(),
            agent_type: AgentType::Custom,
            command: Some("my-agent run".into()),
            endpoint: None,
            capabilities: vec!["implement".into()],
        });

        let agents = orchestrator.list_agents();
        assert_eq!(agents.len(), 4);
        assert!(agents.iter().any(|a| a.id == "my-agent"));
    }

    #[test]
    fn test_register_replaces_existing() {
        let mut orchestrator = AgentOrchestrator::new();

        orchestrator.register_agent(AgentConfig {
            id: "claude-code".into(),
            name: "Custom Claude".into(),
            agent_type: AgentType::ClaudeCode,
            command: Some("claude --custom".into()),
            endpoint: None,
            capabilities: vec![],
        });

        let agents = orchestrator.list_agents();
        // 仍然是 3 个（cursor + copilot + 替换后的 claude-code）
        assert_eq!(agents.len(), 3);
        let claude = agents.iter().find(|a| a.id == "claude-code").unwrap();
        assert_eq!(claude.name, "Custom Claude");
    }

    #[test]
    fn test_get_agent() {
        let orchestrator = AgentOrchestrator::new();
        assert!(orchestrator.get_agent("claude-code").is_some());
        assert!(orchestrator.get_agent("nonexistent").is_none());
    }

    #[test]
    fn test_format_handoff_markdown() {
        let orchestrator = AgentOrchestrator::new();

        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-1".into()),
                epic_id: EpicId("e-1".into()),
                title: "实现用户登录".into(),
                description: "添加 OAuth2 登录支持".into(),
                status: TicketStatus::InProgress,
                assignee: Some("claude-code".into()),
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "Step 1: Add auth middleware\nStep 2: Implement login endpoint".into(),
            context_files: vec![FileContext {
                path: "src/main.rs".into(),
                content: "fn main() {}".into(),
                language: "rust".into(),
            }],
            instructions: "请实现 OAuth2 登录功能".into(),
            verification_prompt: Some("确保密码不以明文存储".into()),
        };

        let md = orchestrator.format_handoff_markdown(&payload);

        assert!(md.contains("# Agent Handoff"));
        assert!(md.contains("实现用户登录"));
        assert!(md.contains("OAuth2"));
        assert!(md.contains("src/main.rs"));
        assert!(md.contains("fn main()"));
        assert!(md.contains("密码不以明文存储"));
        assert!(md.contains("claude-code")); // assignee
    }

    #[test]
    fn test_format_handoff_markdown_minimal() {
        let orchestrator = AgentOrchestrator::new();

        let payload = HandoffPayload {
            ticket: Ticket {
                id: TicketId("t-1".into()),
                epic_id: EpicId("e-1".into()),
                title: "简单任务".into(),
                description: "做一件事".into(),
                status: TicketStatus::Todo,
                assignee: None,
                is_streaming: false,
                spec_refs: vec![],
                created_at: String::new(),
                updated_at: String::new(),
            },
            plan_snapshot: "just do it".into(),
            context_files: vec![],
            instructions: "直接做".into(),
            verification_prompt: None,
        };

        let md = orchestrator.format_handoff_markdown(&payload);

        assert!(md.contains("简单任务"));
        // 没有上下文文件时不应出现 Context Files 节
        assert!(!md.contains("Context Files"));
        // 没有验证提示时不应出现 Verification Prompt 节
        assert!(!md.contains("Verification Prompt"));
    }
}
